"""
DOBO CAD Kernel

Wire Extrusion Engine

Converts WireBuildResult into validated Solid geometry.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

import cadquery as cq

from kernel.contracts.extrusion_profile import (
    ExtrusionMode,
    ExtrusionProfile,
)
from kernel.contracts.solid import (
    BoundingBox,
    Solid,
    SolidValidation,
)
from kernel.services.wire_builder import (
    WireBuildResult,
)


class WireExtrusionEngineInterface(ABC):
    """
    Public interface for Wire extrusion engines.
    """

    @abstractmethod
    def extrude(
        self,
        wire_result: WireBuildResult,
        profile: ExtrusionProfile,
    ) -> Solid:
        """
        Extrudes generated Wires into Solid geometry.
        """


class WireExtrusionEngine(
    WireExtrusionEngineInterface,
):
    """
    Extrudes CadQuery Wires generated by WireBuilder.

    Current support:

    - Normal extrusion
    - One closed Wire per independent solid
    """

    def extrude(
        self,
        wire_result: WireBuildResult,
        profile: ExtrusionProfile,
    ) -> Solid:
        """
        Creates and validates Solid geometry.
        """

        wire_result.validate()
        profile.validate()

        if profile.mode != ExtrusionMode.NORMAL:
            raise NotImplementedError(
                "WireExtrusionEngine currently supports "
                "normal extrusion only."
            )

        direction = self._read_projection_normal(
            wire_result
        )

        extrusion_vector = cq.Vector(
            direction[0] * profile.depth,
            direction[1] * profile.depth,
            direction[2] * profile.depth,
        )

        generated_solids: list[cq.Shape] = []

        for wire in wire_result.wires:
            try:
                generated_shape = (
                    cq.Solid.extrudeLinear(
                        wire,
                        [],
                        extrusion_vector,
                    )
                )

                generated_shape = (
                    generated_shape.clean()
                )

            except Exception as error:
                raise RuntimeError(
                    "WireExtrusionEngine could not "
                    "extrude a generated Wire."
                ) from error

            if not isinstance(
                generated_shape,
                cq.Shape,
            ):
                raise RuntimeError(
                    "WireExtrusionEngine did not produce "
                    "CadQuery Shape geometry."
                )

            if not generated_shape.isValid():
                raise RuntimeError(
                    "WireExtrusionEngine generated "
                    "an invalid CAD solid."
                )

            if generated_shape.Volume() <= 0:
                raise RuntimeError(
                    "WireExtrusionEngine generated "
                    "zero-volume geometry."
                )

            generated_solids.append(
                generated_shape
            )

        if not generated_solids:
            raise RuntimeError(
                "WireExtrusionEngine generated no solids."
            )

        geometry = self._combine_solids(
            generated_solids
        )

        return self._build_solid_contract(
            geometry=geometry,
            profile=profile,
            wire_result=wire_result,
        )

    @staticmethod
    def _read_projection_normal(
        wire_result: WireBuildResult,
    ) -> tuple[float, float, float]:
        """
        Reads the extrusion normal stored by
        GeometryProjectionEngine.
        """

        raw_normal = (
            wire_result
            .source
            .metadata
            .get(
                "normal"
            )
        )

        if raw_normal is not None:
            if not isinstance(
                raw_normal,
                (
                    tuple,
                    list,
                ),
            ) or len(raw_normal) != 3:
                raise ValueError(
                    "Projected contour normal must "
                    "contain three values."
                )

            return (
                float(raw_normal[0]),
                float(raw_normal[1]),
                float(raw_normal[2]),
            )

        surface_type = (
            wire_result
            .source
            .metadata
            .get(
                "surface_type"
            )
        )

        if surface_type == "plane":
            return (
                0.0,
                0.0,
                1.0,
            )

        raise ValueError(
            "WireExtrusionEngine requires an extrusion "
            "normal in projected contour metadata."
        )

    @staticmethod
    def _combine_solids(
        solids: list[cq.Shape],
    ) -> cq.Shape:
        """
        Combines all generated solids.
        """

        if len(solids) == 1:
            return solids[0]

        try:
            combined = solids[0].fuse(
                *solids[1:]
            )

            combined = combined.clean()

        except Exception as error:
            raise RuntimeError(
                "WireExtrusionEngine could not combine "
                "the generated solids."
            ) from error

        if not isinstance(
            combined,
            cq.Shape,
        ):
            raise RuntimeError(
                "Combined extrusion result is not "
                "a CadQuery Shape."
            )

        if not combined.isValid():
            raise RuntimeError(
                "Combined extrusion geometry is invalid."
            )

        return combined

    @staticmethod
    def _build_solid_contract(
        geometry: cq.Shape,
        profile: ExtrusionProfile,
        wire_result: WireBuildResult,
    ) -> Solid:
        """
        Converts CadQuery geometry into a Solid contract.
        """

        volume = float(
            geometry.Volume()
        )

        center = geometry.Center()
        box = geometry.BoundingBox()

        result = Solid(
            geometry=geometry,
            volume=volume,
            center_of_mass=(
                float(center.x),
                float(center.y),
                float(center.z),
            ),
            bounding_box=BoundingBox(
                minimum=(
                    float(box.xmin),
                    float(box.ymin),
                    float(box.zmin),
                ),
                maximum=(
                    float(box.xmax),
                    float(box.ymax),
                    float(box.zmax),
                ),
            ),
            validation=SolidValidation(
                is_valid=bool(
                    geometry.isValid()
                ),
                is_closed=True,
                is_manifold=True,
                is_watertight=True,
                errors=(),
                warnings=(),
            ),
            source="wire_extrusion_engine",
            metadata={
                "mode": profile.mode.value,
                "depth": profile.depth,
                "wire_count": (
                    wire_result.count
                ),
                "surface_type": (
                    wire_result
                    .source
                    .metadata
                    .get(
                        "surface_type"
                    )
                ),
            },
        )

        result.validate()

        return result