"""
DOBO CAD Kernel

Boolean Configuration Contract

Defines how a generated Solid must interact
with the current ModelState.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from kernel.contracts.boolean_request import (
    BooleanOperation,
)


@dataclass(frozen=True, slots=True)
class BooleanConfiguration:
    """
    Configuration for one Boolean stage execution.

    The Solid operand is generated by the previous
    Extrusion stage and is therefore not stored here.
    """

    operation: BooleanOperation = (
        BooleanOperation.UNION
    )

    tolerance: float = 0.01

    priority: int = 0

    label: str = ""

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    def validate(self) -> None:
        """
        Validates the Boolean configuration.
        """

        if self.tolerance <= 0:
            raise ValueError(
                "BooleanConfiguration tolerance "
                "must be greater than zero."
            )

        if not isinstance(
            self.priority,
            int,
        ):
            raise TypeError(
                "BooleanConfiguration priority "
                "must be an integer."
            )

        if not isinstance(
            self.metadata,
            dict,
        ):
            raise TypeError(
                "BooleanConfiguration metadata "
                "must be a dictionary."
            )