"""Semantic design interpretation contracts for the DOBO platform."""

from .semantic_contract import (
    Ambiguity,
    Assumption,
    BodyIntent,
    DesignSemanticProgram,
    FeatureIntent,
    FeatureSizeIntent,
    ManufacturingIntent,
    SemanticAnchor,
    SemanticRelation,
    SourceIntent,
)
from .semantic_parser import SemanticProgramParser
from .prompt_interpreter import (
    OpenAIResponsesSemanticClient,
    PromptInterpretationResult,
    PromptInterpretationTrace,
    PromptSemanticInterpreter,
    SemanticModelClient,
    SemanticModelResponse,
)
from .semantic_compiler import (
    CompilationTrace,
    SemanticCompilationReport,
    SemanticCompilationResult,
    SemanticToMotorCompiler,
)
from .image_interpreter import (
    ImageInterpretationResult,
    ImageInterpretationTrace,
    ImageModelClient,
    ImageModelResponse,
    ImageSemanticInterpreter,
    OpenAIResponsesImageClient,
)
from .proposal_repair import (
    ProposalValidationSnapshot,
    SemanticProposalRepairer,
    SemanticRepairAction,
    SemanticRepairReport,
    SemanticRepairResult,
)
from .design_pipeline import (
    DesignPipelineResult,
    DesignPipelineTrace,
    DoboDesignPipeline,
)
from .three_mf_export import ThreeMFExportResult, ThreeMFMeshExporter
from .structural_vocabulary import (
    StructuralAnchor,
    StructuralDesignProgram,
    StructuralFeature,
    StructuralVisualGroup,
    StructuralVocabularyResolver,
)
from .design_grammar import (
    ACCEPTANCE_MATRIX_VERSION,
    BODY_GRAMMAR_VERSION,
    COMPONENT_GRAMMAR_VERSION,
    COMPOSITION_GRAMMAR_VERSION,
    STYLE_GRAMMAR_VERSION,
    DesignGrammarPlan,
    DesignGrammarResolver,
    GrammarFeaturePlan,
    GrammarStyleProfile,
)
from .structural_compiler import (
    STRUCTURAL_COMPILER_VERSION,
    STRUCTURAL_HIERARCHY_VERSION,
    STRUCTURAL_TEMPLATE_VERSION,
    StructuralCompilationReport,
    StructuralCompilationResult,
    StructuralSemanticCompiler,
)
from .structural_pipeline import (
    STRUCTURAL_FUSION_VERSION,
    STRUCTURAL_PIPELINE_VERSION,
    DoboStructuralPipeline,
    StructuralPipelineResult,
    StructuralPipelineTrace,
)

__all__ = (
    "Ambiguity",
    "Assumption",
    "BodyIntent",
    "DesignSemanticProgram",
    "FeatureIntent",
    "FeatureSizeIntent",
    "ManufacturingIntent",
    "SemanticAnchor",
    "OpenAIResponsesSemanticClient",
    "PromptInterpretationResult",
    "PromptInterpretationTrace",
    "PromptSemanticInterpreter",
    "SemanticModelClient",
    "SemanticModelResponse",
    "CompilationTrace",
    "SemanticCompilationReport",
    "SemanticCompilationResult",
    "SemanticToMotorCompiler",
    "ImageInterpretationResult",
    "ImageInterpretationTrace",
    "ImageModelClient",
    "ImageModelResponse",
    "ImageSemanticInterpreter",
    "OpenAIResponsesImageClient",
    "ProposalValidationSnapshot",
    "SemanticProposalRepairer",
    "SemanticRepairAction",
    "SemanticRepairReport",
    "SemanticRepairResult",
    "DesignPipelineResult",
    "DesignPipelineTrace",
    "DoboDesignPipeline",
    "ThreeMFExportResult",
    "ThreeMFMeshExporter",
    "StructuralAnchor",
    "StructuralDesignProgram",
    "StructuralFeature",
    "StructuralVisualGroup",
    "StructuralVocabularyResolver",
    "DesignGrammarPlan",
    "DesignGrammarResolver",
    "GrammarFeaturePlan",
    "GrammarStyleProfile",
    "BODY_GRAMMAR_VERSION",
    "COMPONENT_GRAMMAR_VERSION",
    "COMPOSITION_GRAMMAR_VERSION",
    "STYLE_GRAMMAR_VERSION",
    "ACCEPTANCE_MATRIX_VERSION",
    "StructuralCompilationReport",
    "StructuralCompilationResult",
    "StructuralSemanticCompiler",
    "STRUCTURAL_COMPILER_VERSION",
    "STRUCTURAL_TEMPLATE_VERSION",
    "STRUCTURAL_HIERARCHY_VERSION",
    "STRUCTURAL_FUSION_VERSION",
    "STRUCTURAL_PIPELINE_VERSION",
    "DoboStructuralPipeline",
    "StructuralPipelineResult",
    "StructuralPipelineTrace",
    "SemanticProgramParser",
    "SemanticRelation",
    "SourceIntent",
)
